### ISSUE TITLE
[Bug]: InAppWebViewのWifiがない状態で、No implementation foundが出力される不具合を修正する

### ISSUE THREAD

**Issue by iseruuuuu** [yumemi-inc/flutter-mobile-project-template#163]
### これに関する既存の Issue はありますか？

- [X] 既存の Issue はありませんでした

### 現在の動作

1.WebView 内で遷移する
2.機内モードをオンにする
3.WebView で Pull-to-Refresh をする
4.エラー画面が表示される
5.エラー画面のリロードボタンを押すと`No implementation found`のエラーがログに出力される。

### 期待される動作
- Wifiがない状態でも、`No implementation found`が呼ばれないようにする。

#### iOS
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getUrl on channel com.pichillilorenzo/flutter_inappwebview_0)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      IOSInAppWebViewController.getUrl (package:flutter_inappwebview_ios/src/in_app_webview/in_app_webview_controller.dart:1555:19)
<asynchronous suspension>
#2      _WebViewState.onRefresh (package:features_webview/src/ui/web_view.dart:42:16)
<asynchronous suspension>
#3      _WebViewState.build.<anonymous closure> (package:features_webview/src/ui/web_view.dart:90:25)
```

#### Android
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPluginException(No implementation found for method getUrl on channel com.pichillilorenzo/flutter_inappwebview_0)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:320:7)
<asynchronous suspension>
#1      IOSInAppWebViewController.getUrl (package:flutter_inappwebview_ios/src/in_app_webview/in_app_webview_controller.dart:1555:19)
<asynchronous suspension>
#2      _WebViewState.onRefresh (package:features_webview/src/ui/web_view.dart:42:16)
<asynchronous suspension>
#3      _WebViewState.build.<anonymous closure> (package:features_webview/src/ui/web_view.dart:90:25)
```

### 備考
#162 に関連がありそうです。

### 環境

```Markdown
- Commit Hash: 0153501e8487f388e99243d36f56509ea98f9def
- App Version: 1.0.0
- Platform: iOS 17.2.1, Android 14 API level 34
```

**Comment by iseruuuuu** [comment]
しばごーさんからInAppWebViewのバグではないかというコメントをいただきました。
https://github.com/pichillilorenzo/flutter_inappwebview/issues/1296

**Comment by blendthink** [comment]
1. WebView のバージョンを最新にして解決すればそれでOK
    - https://pub.dev/packages/flutter_inappwebview/versions/6.1.5
2. 解決しない場合はなぜエラーが出力されるか調査

**Comment by karas1910** [comment]
`Visibility.maintain` に変更することでエラーログがでないことを確認しました。
#162 で対応する予定のため、こちらのissueをクローズさせていただきます。
